[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/devendrakushwah"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://linkedin.com/in/devendrakushwah"

[social.params]
icon = "brand-linkedin"
